
//! Autogenerated weights for `xx_cmix`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2025-12-13, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Mac.carback.int`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/xxnetwork-chain
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/xxnetwork-runtime/xxnetwork_runtime.compact.compressed.wasm
// --genesis-builder
// none
// --pallet
// xx_cmix
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages
// 4096
// --output
// ./runtime/xxnetwork/src/weights/xx_cmix.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `xx_cmix`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> xx_cmix::WeightInfo for WeightInfo<T> {
	/// Storage: `XXCmix::AdminPermission` (r:1 w:0)
	/// Proof: `XXCmix::AdminPermission` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `XXCmix::CmixHashes` (r:0 w:1)
	/// Proof: `XXCmix::CmixHashes` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_cmix_hashes() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `8`
		//  Estimated: `1493`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(8_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1493))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `XXCmix::SchedulingAccount` (r:0 w:1)
	/// Proof: `XXCmix::SchedulingAccount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_scheduling_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `XXCmix::NextCmixVariables` (r:0 w:1)
	/// Proof: `XXCmix::NextCmixVariables` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_next_cmix_variables() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(2_000_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `XXCmix::SchedulingAccount` (r:1 w:0)
	/// Proof: `XXCmix::SchedulingAccount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Staking::ActiveEra` (r:1 w:0)
	/// Proof: `Staking::ActiveEra` (`max_values`: Some(1), `max_size`: Some(13), added: 508, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 99]`.
	fn submit_cmix_points(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `37`
		//  Estimated: `1522`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_636_321, 0)
			.saturating_add(Weight::from_parts(0, 1522))
			// Standard Error: 553
			.saturating_add(Weight::from_parts(3_913, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `XXCmix::SchedulingAccount` (r:1 w:0)
	/// Proof: `XXCmix::SchedulingAccount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Staking::ActiveEra` (r:1 w:0)
	/// Proof: `Staking::ActiveEra` (`max_values`: Some(1), `max_size`: Some(13), added: 508, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 99]`.
	fn submit_cmix_deductions(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `37`
		//  Estimated: `1522`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_452_809, 0)
			.saturating_add(Weight::from_parts(0, 1522))
			// Standard Error: 778
			.saturating_add(Weight::from_parts(1_543, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `XXCmix::SchedulingAccount` (r:1 w:0)
	/// Proof: `XXCmix::SchedulingAccount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `XXCmix::CmixAddressSpace` (r:0 w:1)
	/// Proof: `XXCmix::CmixAddressSpace` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_cmix_address_space() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `37`
		//  Estimated: `1522`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1522))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `XXCmix::AdminPermission` (r:0 w:1)
	/// Proof: `XXCmix::AdminPermission` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_admin_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
