[package]
name = "node-rpc"
version = "0.2.0"
authors = ["xxlabs <admin@xx.network>"]
edition = "2021"
homepage = "https://xx.network"
repository = "https://github.com/xx-labs/xxchain/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { version = "0.24", features = ["server"] }
node-primitives = { workspace = true, features = ["std"] }
pallet-transaction-payment-rpc = { workspace = true }
sc-client-api = { workspace = true }
sc-consensus-babe = { workspace = true }
sc-consensus-babe-rpc = { workspace = true }
sc-chain-spec = { workspace = true }
sc-consensus-grandpa = { workspace = true }
sc-consensus-grandpa-rpc = { workspace = true }
sc-rpc-api = { workspace = true }
sc-rpc = { workspace = true }
sc-sync-state-rpc = { workspace = true }
sp-api = { workspace = true, features = ["std"] }
sp-block-builder = { workspace = true, features = ["std"] }
sp-blockchain = { workspace = true }
sp-keystore = { workspace = true }
sp-consensus = { workspace = true }
sp-consensus-babe = { workspace = true, features = ["std"] }
sp-runtime = { workspace = true, features = ["std"] }
sc-transaction-pool-api = { workspace = true }
substrate-frame-rpc-system = { workspace = true }
