[package]
name = "migrations"
version = "0.1.0"
authors = ["Bernardo Cardoso <bernardo@xx.network>"]
edition = "2021"

[dependencies]
log = { workspace = true }
codec = { workspace = true }

# frame dependencies
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-runtime = { workspace = true }
sp-io = { workspace = true }

# staking
pallet-staking = { workspace = true }

# chainbridge
chainbridge = { workspace = true }

# xx pallets
xx-economics = { workspace = true }
xx-staking-extension = { workspace = true }

[features]
default = ["std"]
std = [
	"log/std",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"sp-runtime/std",
	"sp-io/std",
	"pallet-staking/std",
	"chainbridge/std",
	"xx-economics/std",
	"xx-staking-extension/std"
]
try-runtime = ["frame-support/try-runtime", "sp-runtime/try-runtime"]
