[package]
name = "runtime-common"
version = "0.2.0"
authors = ["xxlabs <admin@xx.network>"]
edition = "2021"
homepage = "https://xx.network"
repository = "https://github.com/xx-labs/xxchain/"

[lints]
workspace = true

[dependencies]
# third-party dependencies
codec = { workspace = true }
static_assertions = { workspace = true }
smallvec = "1.7.0"

# primitives
sp-runtime = { workspace = true }
sp-staking = { workspace = true }
sp-io = { workspace = true }
node-primitives = { workspace = true }

# frame dependencies
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-election-provider-support = { workspace = true }

# pallets
pallet-authorship = { workspace = true }
pallet-balances = { workspace = true }
pallet-transaction-payment = { workspace = true }
pallet-treasury = { workspace = true }
pallet-staking = { workspace = true }
pallet-election-provider-multi-phase = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"node-primitives/std",
	"sp-staking/std",
	"sp-io/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"frame-election-provider-support/std",
	"pallet-transaction-payment/std",
	"pallet-treasury/std",
	"pallet-staking/std",
	"pallet-election-provider-multi-phase/std",
]
fast-runtime = []
